name: scandit_flutter_datacapture_id_voided_detection
description: ScanditIdVoidedDetection is a library that enables Voided ID Detection capabilities.
version: 8.1.1
homepage: https://scandit.com

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.id_voided_detection
        pluginClass: ScanditFlutterDataCaptureIdVoidedDetectionPlugin
      ios:
        pluginClass: ScanditFlutterDatacaptureIdVoidedDetectionPlugin
